// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimestampBitProtos.proto

package com.hbase.test;

public final class TimestampBitProtos {
  private TimestampBitProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TimestampBitComparatorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 skip = 1;
    /**
     * <code>required int32 skip = 1;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    boolean hasSkip();
    /**
     * <code>required int32 skip = 1;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    int getSkip();

    // required string data = 2;
    /**
     * <code>required string data = 2;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    boolean hasData();
    /**
     * <code>required string data = 2;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    java.lang.String getData();
    /**
     * <code>required string data = 2;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code com.hbase.test.TimestampBitComparator}
   */
  public static final class TimestampBitComparator extends
      com.google.protobuf.GeneratedMessage
      implements TimestampBitComparatorOrBuilder {
    // Use TimestampBitComparator.newBuilder() to construct.
    private TimestampBitComparator(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TimestampBitComparator(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TimestampBitComparator defaultInstance;
    public static TimestampBitComparator getDefaultInstance() {
      return defaultInstance;
    }

    public TimestampBitComparator getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TimestampBitComparator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              skip_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hbase.test.TimestampBitProtos.internal_static_com_hbase_test_TimestampBitComparator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hbase.test.TimestampBitProtos.internal_static_com_hbase_test_TimestampBitComparator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hbase.test.TimestampBitProtos.TimestampBitComparator.class, com.hbase.test.TimestampBitProtos.TimestampBitComparator.Builder.class);
    }

    public static com.google.protobuf.Parser<TimestampBitComparator> PARSER =
        new com.google.protobuf.AbstractParser<TimestampBitComparator>() {
      public TimestampBitComparator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimestampBitComparator(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TimestampBitComparator> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 skip = 1;
    public static final int SKIP_FIELD_NUMBER = 1;
    private int skip_;
    /**
     * <code>required int32 skip = 1;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    public boolean hasSkip() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 skip = 1;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    public int getSkip() {
      return skip_;
    }

    // required string data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.lang.Object data_;
    /**
     * <code>required string data = 2;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string data = 2;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          data_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string data = 2;</code>
     *
     * <pre>
     *自定义比较器中需序列化的字段
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      skip_ = 0;
      data_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSkip()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, skip_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDataBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, skip_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDataBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hbase.test.TimestampBitProtos.TimestampBitComparator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hbase.test.TimestampBitProtos.TimestampBitComparator prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hbase.test.TimestampBitComparator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hbase.test.TimestampBitProtos.TimestampBitComparatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hbase.test.TimestampBitProtos.internal_static_com_hbase_test_TimestampBitComparator_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hbase.test.TimestampBitProtos.internal_static_com_hbase_test_TimestampBitComparator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hbase.test.TimestampBitProtos.TimestampBitComparator.class, com.hbase.test.TimestampBitProtos.TimestampBitComparator.Builder.class);
      }

      // Construct using com.hbase.test.TimestampBitProtos.TimestampBitComparator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        skip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hbase.test.TimestampBitProtos.internal_static_com_hbase_test_TimestampBitComparator_descriptor;
      }

      public com.hbase.test.TimestampBitProtos.TimestampBitComparator getDefaultInstanceForType() {
        return com.hbase.test.TimestampBitProtos.TimestampBitComparator.getDefaultInstance();
      }

      public com.hbase.test.TimestampBitProtos.TimestampBitComparator build() {
        com.hbase.test.TimestampBitProtos.TimestampBitComparator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hbase.test.TimestampBitProtos.TimestampBitComparator buildPartial() {
        com.hbase.test.TimestampBitProtos.TimestampBitComparator result = new com.hbase.test.TimestampBitProtos.TimestampBitComparator(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.skip_ = skip_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hbase.test.TimestampBitProtos.TimestampBitComparator) {
          return mergeFrom((com.hbase.test.TimestampBitProtos.TimestampBitComparator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hbase.test.TimestampBitProtos.TimestampBitComparator other) {
        if (other == com.hbase.test.TimestampBitProtos.TimestampBitComparator.getDefaultInstance()) return this;
        if (other.hasSkip()) {
          setSkip(other.getSkip());
        }
        if (other.hasData()) {
          bitField0_ |= 0x00000002;
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSkip()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hbase.test.TimestampBitProtos.TimestampBitComparator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hbase.test.TimestampBitProtos.TimestampBitComparator) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 skip = 1;
      private int skip_ ;
      /**
       * <code>required int32 skip = 1;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public boolean hasSkip() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 skip = 1;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public int getSkip() {
        return skip_;
      }
      /**
       * <code>required int32 skip = 1;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public Builder setSkip(int value) {
        bitField0_ |= 0x00000001;
        skip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 skip = 1;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public Builder clearSkip() {
        bitField0_ = (bitField0_ & ~0x00000001);
        skip_ = 0;
        onChanged();
        return this;
      }

      // required string data = 2;
      private java.lang.Object data_ = "";
      /**
       * <code>required string data = 2;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string data = 2;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string data = 2;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string data = 2;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 2;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>required string data = 2;</code>
       *
       * <pre>
       *自定义比较器中需序列化的字段
       * </pre>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.hbase.test.TimestampBitComparator)
    }

    static {
      defaultInstance = new TimestampBitComparator(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hbase.test.TimestampBitComparator)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hbase_test_TimestampBitComparator_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hbase_test_TimestampBitComparator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030TimestampBitProtos.proto\022\016com.hbase.te" +
      "st\"4\n\026TimestampBitComparator\022\014\n\004skip\030\001 \002" +
      "(\005\022\014\n\004data\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hbase_test_TimestampBitComparator_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hbase_test_TimestampBitComparator_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hbase_test_TimestampBitComparator_descriptor,
              new java.lang.String[] { "Skip", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
